<?php

namespace Database\Seeders;

use App\Models\BusinessType;
use Illuminate\Database\Seeder;

class BusinessTypeSeeder extends Seeder
{
    public function run()
    {
        // =========================================================
        // 1. 質屋
        // =========================================================
        BusinessType::updateOrCreate(['slug' => 'pawn'], [
            'name'       => '質屋・買取店',
            'base_context' => '質屋・買取店でのサービス体験（査定・買取・質入れなど）',
            'sort_order' => 1,
            'is_active'  => true,
            'use_pawn_system'    => true,
            'use_purchase_posts' => true,
            'use_product_rank'   => true,
            'post_action_word'   => 'お買取り',
            'post_title_template' => '{brand} {product} {status}をお買取りいたしました。人気の{brand}の{category}は状態を問わず高価買取中です。',
            'post_status_options' => ['中古品', '新品', '未使用品'],
            'post_reason_presets' => ['使わなくなったため', '引っ越しのため', '買い替えのため', '資金が必要なため', '断捨離・整理のため', '遺品整理のため', 'プレゼントだが不要になった'],
            'post_accessory_presets' => ['箱', '保証書', '説明書', '替えベルト', '充電器', 'ケース', '袋', 'ギャランティカード', '鑑定書', 'コマ'],
            'post_categories' => [
                ['name' => 'ゲーム・ソフト', 'wp_slug' => 'ゲーム', 'wp_path' => '/items/other'],
                ['name' => '時計', 'wp_slug' => '時計', 'wp_path' => '/items/clock'],
                ['name' => 'ブランド品', 'wp_slug' => 'ブランド品', 'wp_path' => '/items/brand'],
                ['name' => '貴金属', 'wp_slug' => 'ジュエリー', 'wp_path' => '/items/gold'],
                ['name' => '金券', 'wp_slug' => '硬貨', 'wp_path' => '/items/other'],
                ['name' => 'カメラ・レンズ', 'wp_slug' => 'カメラ', 'wp_path' => '/items/camera'],
                ['name' => '電化製品', 'wp_slug' => 'パソコン', 'wp_path' => '/items/electricity'],
                ['name' => '電動工具', 'wp_slug' => 'スポーツ用品', 'wp_path' => '/items/electric-tool'],
                ['name' => 'お酒', 'wp_slug' => 'アルコール', 'wp_path' => '/items/other'],
                ['name' => 'スマホ・タブレット', 'wp_slug' => 'スマホ・タブレット', 'wp_path' => '/items/smartphone'],
                ['name' => '楽器', 'wp_slug' => '楽器', 'wp_path' => '/items/instrument'],
                ['name' => 'ダイヤモンド', 'wp_slug' => 'ダイヤモンド', 'wp_path' => '/items/gold'],
                ['name' => 'プラチナ', 'wp_slug' => 'プラチナ', 'wp_path' => '/items/gold'],
                ['name' => '宝石', 'wp_slug' => '宝石', 'wp_path' => '/items/gold'],
                ['name' => 'DVDブルーレイ', 'wp_slug' => 'DVDブルーレイ', 'wp_path' => '/items/other'],
                ['name' => 'おもちゃ', 'wp_slug' => 'おもちゃ', 'wp_path' => '/items/other'],
                ['name' => 'フィギュア', 'wp_slug' => 'フィギュア', 'wp_path' => '/items/other'],
                ['name' => '健康器具', 'wp_slug' => '健康器具', 'wp_path' => '/items/other'],
                ['name' => 'カー用品', 'wp_slug' => 'カー用品', 'wp_path' => '/items/other'],
            ],
            'visit_type_options' => ['初めての来店', 'リピーター', '家族と来店', '知人の紹介'],
            'review_item_options' => ['ブランド品', '貴金属', '時計', 'お酒', 'スマホ', 'その他'],
            'review_option_groups' => [
                ['key' => 'gender',     'label' => '性別',   'options' => ['男性', '女性'], 'enabled' => true],
                ['key' => 'visit_type', 'label' => '来店',   'options' => ['初めての来店', 'リピーター', '家族と来店', '知人の紹介'], 'enabled' => true],
                ['key' => 'age',        'label' => '年代',   'options' => ['20代', '30代', '40代', '50代', '60代~'], 'enabled' => true],
                ['key' => 'item',       'label' => '品目',   'options' => ['ブランド品', '貴金属', '時計', 'お酒', 'スマホ', 'その他'], 'enabled' => true],
            ],
            'focus_presets' => [
                'お店の雰囲気や居心地も交えて',
                '結果（査定額や対応）を中心に',
                '相談しやすい雰囲気だったことを中心に',
                'また来たいという気持ちを中心に',
                'スタッフへの感謝を中心に',
                '予想以上に満足できたことを中心に',
                '対応のスピード感を中心に',
                '説明の丁寧さ・わかりやすさを中心に',
                '店内の清潔感や印象を交えて',
                '思っていたより良かった驚きを中心に',
                '気軽に相談できる雰囲気を中心に',
                '接客の距離感がちょうど良かったことを中心に',
                '知人にもすすめたいという気持ちを中心に',
                '緊張していたけど安心できたことを中心に',
                '立地やアクセスの良さにも触れて',
                '待ち時間が短くスムーズだったことを中心に',
                '無理な営業がなく安心だったことを中心に',
                '納得のいく説明をしてもらえたことを中心に',
                '安心して大切な品物を任せられたと感じたことを中心に',
                '不安だった気持ちが解消されたことを中心に',
            ],
            'style_presets' => [
                '初めてこの店を利用した新規のお客様',
                '何度も利用しているリピーターのお客様',
                '家族や友人に紹介したいと思っているタイプ',
                'ネットで他店と比較してから来店した慎重なタイプ',
                '普段あまり口コミを書かない素朴なタイプ',
                '短文でサクッと書くタイプ',
                '感謝の気持ちをしっかり伝えたいタイプ',
                '仕事の合間にサッと立ち寄った忙しいタイプ',
                '引っ越しや大掃除をきっかけに来店したタイプ',
                '久しぶりに利用して改めて良さを実感したタイプ',
                '家族に勧められて来店したタイプ',
                '口コミを見て来店を決めたタイプ',
                '通りがかりにふらっと入ってみたタイプ',
                '買い替え資金のために持ち込んだタイプ',
                'たまたま近くに用事があって立ち寄ったタイプ',
                '他の人の参考になればと思って書いているタイプ',
                '質屋に対する先入観が変わったタイプ',
            ],
            'ng_words' => [
                '借金', '返済', '生活費', 'お金に困って', '金欠',
                '離婚', '元妻', '元夫', '別れた', '元カノ', '元カレ',
                '病気', '入院', '手術費', '治療費', '闘病',
                'ロレックス', 'ルイヴィトン', 'シャネル', 'エルメス',
                'ギャンブル', 'パチンコ', '競馬', 'スロット',
                '亡くなった', '遺品', '形見', '故人', '供養',
            ],
        ]);

        // =========================================================
        // 2. 焼肉店
        // =========================================================
        BusinessType::updateOrCreate(['slug' => 'yakiniku'], [
            'name'       => '焼肉店',
            'base_context' => '焼肉店での食事・接客・雰囲気に関する体験',
            'sort_order' => 2,
            'is_active'  => true,
            'use_pawn_system'    => false,
            'use_purchase_posts' => false,
            'use_product_rank'   => false,
            'post_action_word'   => 'ご提供',
            'post_title_template' => '{brand} {product}のご紹介です。{category}メニューをお探しの方はぜひご来店ください。',
            'post_status_options' => ['通常メニュー', '期間限定', '新メニュー'],
            'post_reason_presets' => ['友人と食事', '家族の食事会', '記念日・お祝い', '会社の飲み会', 'デート', 'ひとり焼肉'],
            'post_accessory_presets' => [],
            'post_categories' => [
                ['name' => 'カルビ・ロース', 'wp_slug' => 'kalbi', 'wp_path' => '/menu/kalbi'],
                ['name' => 'ホルモン', 'wp_slug' => 'horumon', 'wp_path' => '/menu/horumon'],
                ['name' => 'セットメニュー', 'wp_slug' => 'set', 'wp_path' => '/menu/set'],
                ['name' => 'サイドメニュー', 'wp_slug' => 'side', 'wp_path' => '/menu/side'],
                ['name' => 'ドリンク', 'wp_slug' => 'drink', 'wp_path' => '/menu/drink'],
            ],
            'visit_type_options' => ['ひとり焼肉', '家族・グループ', 'デート', '会社の飲み会', '記念日利用'],
            'review_item_options' => ['焼肉コース', '単品メニュー', 'ホルモン', 'お酒・ドリンク', 'ランチ', 'その他'],
            'review_option_groups' => [
                ['key' => 'gender',     'label' => '性別', 'options' => ['男性', '女性'], 'enabled' => true],
                ['key' => 'visit_type', 'label' => '来店', 'options' => ['ひとり焼肉', '家族・グループ', 'デート', '会社の飲み会', '記念日利用'], 'enabled' => true],
                ['key' => 'age',        'label' => '年代', 'options' => ['20代', '30代', '40代', '50代', '60代~'], 'enabled' => true],
                ['key' => 'item',       'label' => '品目', 'options' => ['焼肉コース', '単品メニュー', 'ホルモン', 'お酒・ドリンク', 'ランチ', 'その他'], 'enabled' => true],
            ],
            'focus_presets' => [
                'お肉の美味しさや鮮度を中心に',
                '個室や席の居心地を中心に',
                'タレや調味料のこだわりを中心に',
                'スタッフの気配りや接客を中心に',
                'コスパの良さを中心に',
                'お肉の種類・メニューの豊富さを中心に',
                'また来たいという気持ちを中心に',
                '記念日や特別な日に使えることを中心に',
                '予約のしやすさや待ち時間の短さを中心に',
                '煙の少なさや店内の快適さを中心に',
                '知人にもすすめたいという気持ちを中心に',
                '食べ放題のお得感を中心に',
                '締めのご飯や麺の美味しさを中心に',
                'ドリンクの種類や飲み放題について',
                'お店の雰囲気や内装の印象を中心に',
            ],
            'style_presets' => [
                '初めてこの店を利用した新規のお客様',
                '何度もリピートしているヘビーユーザー',
                '家族での食事に来店したタイプ',
                '記念日や誕生日に利用したタイプ',
                '会社の仲間と来店したタイプ',
                'デートで利用したタイプ',
                'グルメにこだわりのあるタイプ',
                'コスパを重視して選んだタイプ',
                '口コミを参考に来店したタイプ',
                '近くに住んでいてよく使うタイプ',
            ],
            'ng_words' => [
                '食中毒', '異物', '腐って', '生焼け',
                '他の店のほうが', '近隣店舗名',
            ],
        ]);

        // =========================================================
        // 3. 中古車販売
        // =========================================================
        BusinessType::updateOrCreate(['slug' => 'car_dealer'], [
            'name'       => '中古車販売・車買取',
            'base_context' => '中古車の購入・査定・買取に関する体験',
            'sort_order' => 3,
            'is_active'  => true,
            'use_pawn_system'    => false,
            'use_purchase_posts' => false,
            'use_product_rank'   => true,
            'post_action_word'   => 'お取り扱い',
            'post_title_template' => '{brand} {product} {status}が入荷しました。{category}をお探しの方はぜひお問い合わせください。',
            'post_status_options' => ['中古車', '新古車', '未使用車', '新車'],
            'post_reason_presets' => ['買い替え', '初めての車購入', '家族が増えた', '通勤用に必要', '趣味の車が欲しい', '下取りに出したい'],
            'post_accessory_presets' => ['保証書', '整備記録簿', '取扱説明書', 'スペアキー', 'フロアマット', 'ETCカード'],
            'post_categories' => [
                ['name' => '軽自動車', 'wp_slug' => 'kei', 'wp_path' => '/cars/kei'],
                ['name' => 'セダン', 'wp_slug' => 'sedan', 'wp_path' => '/cars/sedan'],
                ['name' => 'SUV', 'wp_slug' => 'suv', 'wp_path' => '/cars/suv'],
                ['name' => 'ミニバン', 'wp_slug' => 'minivan', 'wp_path' => '/cars/minivan'],
                ['name' => 'トラック・商用車', 'wp_slug' => 'truck', 'wp_path' => '/cars/truck'],
            ],
            'visit_type_options' => ['車の購入', '車の買取・下取り', '試乗', '相談・見積もり', '車検・メンテナンス'],
            'review_item_options' => ['新車', '中古車（軽自動車）', '中古車（普通車）', 'SUV', 'ミニバン', 'その他'],
            'review_option_groups' => [
                ['key' => 'gender',     'label' => '性別', 'options' => ['男性', '女性'], 'enabled' => true],
                ['key' => 'visit_type', 'label' => '目的', 'options' => ['車の購入', '買取・下取り', '試乗', '相談・見積もり', '車検・メンテナンス'], 'enabled' => true],
                ['key' => 'age',        'label' => '年代', 'options' => ['20代', '30代', '40代', '50代', '60代~'], 'enabled' => true],
                ['key' => 'item',       'label' => '車種', 'options' => ['新車', '中古軽自動車', '中古普通車', 'SUV', 'ミニバン', 'その他'], 'enabled' => true],
            ],
            'focus_presets' => [
                '担当スタッフの親切な説明を中心に',
                '車の状態や品質の良さを中心に',
                '査定額の納得感を中心に',
                '手続きのスムーズさを中心に',
                '希望通りの車が見つかったことを中心に',
                '無理な押し売りがなく安心だったことを中心に',
                'アフターサポートの充実を中心に',
                '試乗での印象を中心に',
                '価格の透明性や誠実さを中心に',
                'また来たいという気持ちを中心に',
                '知人にもすすめたいという気持ちを中心に',
                '店舗の清潔感や展示の充実度を中心に',
                '待ち時間が短くスムーズだったことを中心に',
                '予算内で希望に合った提案をしてもらえたことを中心に',
            ],
            'style_presets' => [
                '初めて中古車を購入したタイプ',
                '複数店舗を比較した上で決めたタイプ',
                '買い替えで利用したタイプ',
                '下取りで来店したタイプ',
                '友人の紹介で来店したタイプ',
                '口コミを見て来店を決めたタイプ',
                '慎重に検討してから購入したタイプ',
                '即決で購入を決めた満足度の高いタイプ',
                '遠方からわざわざ来店したタイプ',
                'ネット掲載の車を見に来たタイプ',
            ],
            'ng_words' => [
                '事故車', '走行距離偽装', '修復歴隠し',
                '他のディーラー名', '取り消し',
            ],
        ]);

        // =========================================================
        // 4. 汎用（業種未選択の店舗向けフォールバック）
        // =========================================================
        BusinessType::updateOrCreate(['slug' => 'general'], [
            'name'       => '汎用（その他）',
            'base_context' => 'お店でのサービス・接客・雰囲気に関する体験',
            'sort_order' => 99,
            'is_active'  => true,
            'use_pawn_system'    => false,
            'use_purchase_posts' => false,
            'use_product_rank'   => false,
            'post_action_word'   => 'ご紹介',
            'post_title_template' => '{brand} {product}のご紹介です。{category}に関するご相談はお気軽にどうぞ。',
            'post_status_options' => ['通常', '新着', 'おすすめ'],
            'post_reason_presets' => ['知人の紹介', 'ネットで見つけた', '以前から気になっていた', 'たまたま通りがかった', 'リピート利用'],
            'post_accessory_presets' => [],
            'post_categories' => [
                ['name' => 'サービス', 'wp_slug' => 'service', 'wp_path' => '/service'],
                ['name' => '商品', 'wp_slug' => 'product', 'wp_path' => '/product'],
                ['name' => 'お知らせ', 'wp_slug' => 'news', 'wp_path' => '/news'],
            ],
            'visit_type_options' => ['初めての来店', 'リピーター', '家族・友人と来店', '知人の紹介'],
            'review_item_options' => ['サービス利用', '商品購入', '相談・問い合わせ', 'その他'],
            'review_option_groups' => [
                ['key' => 'gender',     'label' => '性別', 'options' => ['男性', '女性'], 'enabled' => true],
                ['key' => 'visit_type', 'label' => '来店', 'options' => ['初めての来店', 'リピーター', '家族・友人と来店', '知人の紹介'], 'enabled' => true],
                ['key' => 'age',        'label' => '年代', 'options' => ['20代', '30代', '40代', '50代', '60代~'], 'enabled' => true],
                ['key' => 'item',       'label' => '目的', 'options' => ['サービス利用', '商品購入', '相談・問い合わせ', 'その他'], 'enabled' => true],
            ],
            'focus_presets' => [
                'お店の雰囲気や居心地も交えて',
                'スタッフの対応を中心に',
                'また来たいという気持ちを中心に',
                'サービスの丁寧さを中心に',
                '予想以上に満足できたことを中心に',
                '知人にもすすめたいという気持ちを中心に',
                '対応のスピード感を中心に',
                '説明の丁寧さ・わかりやすさを中心に',
                '立地やアクセスの良さにも触れて',
                '待ち時間が短くスムーズだったことを中心に',
            ],
            'style_presets' => [
                '初めてこの店を利用した新規のお客様',
                '何度も利用しているリピーターのお客様',
                '家族や友人に紹介したいと思っているタイプ',
                '普段あまり口コミを書かない素朴なタイプ',
                '短文でサクッと書くタイプ',
                '感謝の気持ちをしっかり伝えたいタイプ',
                '口コミを見て来店を決めたタイプ',
            ],
            'ng_words' => [],
        ]);
    }
}
